Repository chargag/oxygen-cs-grp1-eq8, pull requests merged in 2023-07, with the labels that each got.

#10 Adding pre-commit
  .pre-commit-config.yaml
  Pipfile
  Pipfile.lock
  README.md
Labels: feature

#8 App configuration and docker
  .env
  .flake8
  .github/workflows/build-publish-img.yml
  .gitignore
  Dockerfile
  Pipfile
  Pipfile.lock
  README.md
  docker.env
  src/main.py
  test/test.py
  test/test_env_vars.py
Labels: feature, infra

#11 Pipeline
  .github/workflows/python-validate.yml
Labels: feature

#12 Fix docker image build
  Dockerfile
  Pipfile
  docker-compose.yml
  docker.env
  requirements-docker.txt
Labels: bug, infra

#16 K8s deploy bd
  k8s/db/deployment.yml
  k8s/db/service.yml
Labels: infra
